
# Site details
lang: en
hostname: meatup.info

# Jekyll config
exclude:
  - bower.json
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Makefile
  - node_modules
  - package.json
  - README.md
future: false
lsi: false
markdown: kramdown
permalink: /posts/:title/
pygments: true
safe: true
timezone: Europe/London
